version: '3.8'

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
      ports: 
        - "3000:3000"
      
  frontend: 
    path: ./src/app
  
  backend: 
    path: ./src/app/api

